from tkinter import*
root = Tk()
root.title("Datos del empleado")
root.geometry("600x300")
nombre = StringVar()
codigo = IntVar()
horas = IntVar()
valor = IntVar()
porcentaje = IntVar()
resultado1 = StringVar()
resultado2 = StringVar()
code = StringVar()
nomb = StringVar()
def datos():
    R = (porcentaje.get())/100
    SB = (horas.get())*(valor.get())
    SN = SB-(SB*R)
    code.set(f"Codigo:{codigo.get()}")
    nomb.set(f"Nombre:{nombre.get()}")
    resultado1.set(f"salario bruto:{SB}")
    resultado2.set(f"salario neto:{SN}")
texto1 = Label(root, text="Codigo del empleado:")
texto1.place(x=30, y=30)
entrada1 = Entry(root, textvariable=codigo)
entrada1.place(x=155, y=30)
texto2 = Label(root, text="Nombre del empleado:")
texto2.place(x=30, y=55)
entrada2 = Entry(root, textvariable=nombre)
entrada2.place(x=160, y=55)
texto3 = Label(root, text="Horas trabajadas al mes:")
texto3.place(x=30, y=80)
entrada3 = Entry(root, textvariable=horas)
entrada3.place(x=165, y=80)
texto4 = Label(root, text="Valor por hora:")
texto4.place(x=30, y=105)
entrada4 = Entry(root, textvariable=valor)
entrada4.place(x=115, y=105)
texto5 = Label(root, text="Porcentaje de retencion:")
texto5.place(x=30, y=130)
entrada5 = Entry(root, textvariable=porcentaje)
entrada5.place(x=165, y=130)
boton1 = Button(root, text="Calcular", command=datos)
boton1.place(x=300, y=250)
cod = Entry(root, textvariable=code, state="disabled")
cod.place(x=30, y=180)
nom = Entry(root, textvariable=nomb, state="disabled")
nom.place(x=150, y=180)
res1 = Entry(root, textvariable=resultado1, state="disabled")
res1.place(x=270, y=180)
res2 = Entry(root, textvariable=resultado2, state="disabled")
res2.place(x=390, y=180)
root.mainloop()