from tkinter import*
root = Tk()
root.title("Datos del empleado")
root.geometry("600x300")
nombre = StringVar()
inscripcion = IntVar()
patrimonio = IntVar()
estrato = IntVar()
matricula = StringVar()
numi = StringVar()
nomb = StringVar()
def datos():
    M = 50000
    if patrimonio.get()>2000000 and estrato.get()>3:
        M = M+((patrimonio.get())*(3/100))
        matricula.set(M)
        numi.set(inscripcion.get())
        nomb.set(nombre.get())
    else:
        matricula.set(M)
        numi.set(inscripcion.get())
        nomb.set(nombre.get())
texto1 = Label(root, text="Nombre del estudiante:")
texto1.place(x=30, y=30)
entrada1 = Entry(root, textvariable=nombre)
entrada1.place(x=155, y=30)
texto2 = Label(root, text="Numero de inscripcion:")
texto2.place(x=30, y=55)
entrada2 = Entry(root, textvariable=inscripcion)
entrada2.place(x=160, y=55)
texto3 = Label(root, text="Patrimonio:")
texto3.place(x=30, y=80)
entrada3 = Entry(root, textvariable=patrimonio)
entrada3.place(x=165, y=80)
texto4 = Label(root, text="Estrato:")
texto4.place(x=30, y=105)
entrada4 = Entry(root, textvariable=estrato)
entrada4.place(x=115, y=105)
boton1 = Button(root, text="Calcular", command=datos)
boton1.place(x=300, y=250)
I = Entry(root, textvariable=numi, state="disabled")
I.place(x=30, y=180)
nom = Entry(root, textvariable=nomb, state="disabled")
nom.place(x=150, y=180)
res1 = Entry(root, textvariable=matricula, state="disabled")
res1.place(x=270, y=180)
text1 = Label(root, text="Inscripcion #")
text1.place(x=30, y=150)
text2 = Label(root, text="Nombre")
text2.place(x=150, y=150)
text3 = Label(root, text="Matricula")
text3.place(x=270, y=150)
root.mainloop()