from tkinter import*
root = Tk()
root.title("Datos del empleado")
root.geometry("600x300")
nombre = StringVar()
horas = IntVar()
valor = IntVar()
resultado = StringVar()
def datos():
    Sm = (valor.get())*(horas.get())
    if Sm>450000:
        resultado.set(f"Nombre:{nombre.get()},Salario:{Sm}")
    else:
        resultado.set(f"Nombre:{nombre.get()}")
texto1 = Label(root, text="Nombre del trabajador:")
texto1.place(x=30, y=30)
entrada1 = Entry(root, textvariable=nombre)
entrada1.place(x=160, y=30)
texto2 = Label(root, text="Valor por hora:")
texto2.place(x=30, y=55)
entrada2 = Entry(root, textvariable=valor)
entrada2.place(x=115, y=55)
texto3 = Label(root, text="Horas trabajadas:")
texto3.place(x=30, y=80)
entrada3 = Entry(root, textvariable=horas)
entrada3.place(x=130, y=80)
boton1 = Button(root, text="Calcular", command=datos)
boton1.place(x=300, y=250)
res = Label(root, textvariable=resultado, state="disabled")
res.place(x=30, y=180)
root.mainloop()