from tkinter import*
import math
root = Tk()
root.title("Ecuación de segundo grado")
root.geometry("600x300")
A = IntVar()
B = IntVar()
C = IntVar()
ig = StringVar()
def resolver():
    disc = (B.get()**2)-(4*A.get()*C.get())
    if disc<0:
        ig.set("La ecuacion no tiene solucion")
    else:
        rz = math.sqrt(disc)
        x1 = (-(B.get())+rz)/(2*A.get())
        x2 = (-(B.get())-rz)/(2*A.get())
        ig.set(f"Solucion 1:{x1},Solucion 2:{x2}")
texto1 = Label(root, text="Ingrese el valor de A:")
texto1.place(x=30, y=30)
texto2 = Label(root, text="Ingrese el valor de B:")
texto2.place(x=30, y=55)
texto3 = Label(root, text="Ingrese el valor de C:")
texto3.place(x=30, y=80)
entrada1 = Entry(root, textvariable=A)
entrada1.place(x=150, y=30)
entrada2 = Entry(root, textvariable=B)
entrada2.place(x=150, y=55)
entrada3 = Entry(root, textvariable=C)
entrada3.place(x=150, y=80)
boton = Button(root, text="Resolver", command=resolver)
boton.place(x=285, y=150)
res = Label(root, textvariable=ig, state="disabled")
res.place(x=30, y=130)
root.mainloop()